### PR TITLE
V2 codebook and v2 data support for basic studies

### PR DESCRIPTION
**Pull request by e-kotov**
At this point, I guess I want to merge it. It has gotten too big for one pull request anyway.
This addresses:
#89 
(it's not just the codebook though, but the full v2 basic studies support, and the new sql files that we needed for that are bilingual. Spanish version are not used at the moment, but they are ready to go whenever we introduce some dual language support in the package)
#92 

Also the `spod_download_data()` is shortened to just `spod_download()` to save some typing.

Other improvements cover documentation and fixing quite a few bugs in the process of testing the v2 data.

### CODE REVIEW

**Comment by e-kotov** [comment]
I have just noticed that our GitHub Actions that do the PR checks actually override the package website even without merging. So for example, if I change some function name and reflect this on the new version of the vignettes (and of course this new function name is also rendered in the Reference index https://ropenspain.github.io/spanishoddata/reference/index.html (in my case `spod_donwload_data()` is shortened to just `spod_download()`). So until the PR is merged, our user facing version of the package from the main branch comes with one function name, and the website provides a different one.

@dieghernan is this intentional with the action that you created for the https://github.com/ropenspain/rostemplate/ ? I have not observed this behavior with the default pkgdown action.

**Comment by Robinlovelace** [comment]
> I have just noticed that our GitHub Actions that do the PR checks actually override the package website even without merging.

Woops, that should be a quick fix to the yml file, will take a look now.

**Comment by Robinlovelace** [comment]
As you say @e-kotov this is a huge PR, let's get it merged and pick up any broken pieces as a result to keep the momentum going is my sense.

**Comment by Robinlovelace** [comment]
#97 should probably be ported upstream, maybe this package can be a test case for the fix!

**Comment by e-kotov** [comment]
> let's get it merged and pick up any broken pieces as a result to keep the momentum going is my sense.

ok merging now.

Closes #89 , #92

**Pull request merged**
